"use client";

import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";

type View = "home" | "knowledge" | "library" | "paths";
type Domain = "数与代数" | "函数" | "几何与三角" | "统计与概率" | "微积分";
type Status = "locked" | "ready" | "learning" | "mastered";
type SourceType = "past" | "mock";

type Topic = { id: string; zh: string; en: string; domain: Domain; prereq?: string; core: string[]; exam: string[]; mistakes: string[] };
type Paper = { id: string; title: string; sourceType: SourceType; year: number; session: string; paper: string; difficulty: string; marks: number; source: string; topicIds: string[]; demo?: boolean; file?: File };

const domains: Domain[] = ["数与代数", "函数", "几何与三角", "统计与概率", "微积分"];
const rawTopics: [string,string,string,Domain,string?][] = [
  ["indices","指数与对数","Indices & logarithms","数与代数"],["sequences","数列与级数","Sequences & series","数与代数","indices"],["binomial","二项式定理","Binomial theorem","数与代数","sequences"],["induction","数学归纳法","Proof by induction","数与代数","sequences"],["complex","复数表示","Complex numbers","数与代数","radians"],["demoivre","棣莫弗定理","De Moivre's theorem","数与代数","complex"],
  ["function","函数语言与定义域","Function concepts & domain","函数"],["transform","函数图像变换","Function transformations","函数","function"],["inverse","复合与反函数","Composite & inverse functions","函数","transform"],["polynomial","多项式与根","Polynomials & roots","函数","function"],["rational","有理函数","Rational functions","函数","polynomial"],["expmodel","指数与对数模型","Exponential & logarithmic models","函数","indices"],
  ["radians","弧度与圆测量","Radians & circular measure","几何与三角"],["sinerule","正弦与余弦定理","Sine & cosine rules","几何与三角","radians"],["identities","三角恒等式","Trigonometric identities","几何与三角","radians"],["trigeq","三角方程","Trigonometric equations","几何与三角","identities"],["vectors","二维与三维向量","Vectors in 2D & 3D","几何与三角","function"],["lines","空间直线","Vector equations of lines","几何与三角","vectors"],
  ["probability","概率规则","Probability rules","统计与概率"],["bayes","条件概率与贝叶斯","Conditional probability & Bayes","统计与概率","probability"],["discrete","离散随机变量","Discrete random variables","统计与概率","probability"],["binomialdist","二项分布","Binomial distribution","统计与概率","discrete"],["normal","正态分布","Normal distribution","统计与概率","discrete"],["testing","假设检验","Hypothesis testing","统计与概率","normal"],
  ["limits","极限与连续性","Limits & continuity","微积分","function"],["differentiate","微分与导数法则","Differentiation","微积分","function"],["optimise","导数建模与最优化","Derivative applications","微积分","differentiate"],["integrate","积分与面积","Integration & area","微积分","differentiate"],["techniques","积分技巧","Integration techniques","微积分","integrate"],["diffeq","微分方程","Differential equations","微积分","techniques"],
];
const topics: Topic[] = rawTopics.map(([id,zh,en,domain,prereq])=>({id,zh,en,domain,prereq,core:["核心定义与表示","公式连接","典型变形"],exam:["单知识点应用","跨章节综合"],mistakes:["条件遗漏","代数化简失误"]}));
const topicById = Object.fromEntries(topics.map(t=>[t.id,t]));
const initialStatuses: Record<string,Status> = {indices:"mastered",function:"mastered",radians:"mastered",probability:"mastered",differentiate:"learning"};

const demoPapers: Paper[] = [
  ["a1","演示真题记录 A01","past",2024,"May","Paper 1","较难",14,"演示元数据",["differentiate","optimise"]],
  ["a2","演示真题记录 A02","past",2024,"May","Paper 2","中等",11,"演示元数据",["normal","testing"]],
  ["a3","演示真题记录 A03","past",2023,"November","Paper 1","挑战",16,"演示元数据",["complex","demoivre"]],
  ["a4","演示真题记录 A04","past",2023,"May","Paper 2","较难",13,"演示元数据",["techniques","diffeq"]],
  ["a5","演示真题记录 A05","past",2022,"May","Paper 1","中等",10,"演示元数据",["polynomial","rational"]],
  ["a6","演示真题记录 A06","past",2022,"November","Paper 2","中等",12,"演示元数据",["vectors","lines"]],
  ["m1","演示模拟题：微积分综合","mock",2026,"Mock","Paper 1","挑战",18,"教师演示",["techniques","diffeq"]],
  ["m2","演示模拟题：概率推断","mock",2026,"Mock","Paper 2","较难",15,"教师演示",["bayes","testing"]],
  ["m3","演示模拟题：复数与三角","mock",2026,"Mock","Paper 1","较难",14,"教师演示",["identities","complex","demoivre"]],
].map(([id,title,sourceType,year,session,paper,difficulty,marks,source,topicIds])=>({id,title,sourceType,year,session,paper,difficulty,marks,source,topicIds,demo:true} as Paper));

const paths = [
  {title:"微积分主线",desc:"从函数语言到微分、积分与微分方程",ids:["function","differentiate","integrate","techniques","diffeq"]},
  {title:"函数与代数",desc:"建立 Paper 1 高频代数工具链",ids:["indices","polynomial","rational","expmodel"]},
  {title:"复数与三角",desc:"连接极形式、弧度与棣莫弗定理",ids:["radians","identities","complex","demoivre"]},
  {title:"概率推断",desc:"从概率规则进入分布与检验",ids:["probability","discrete","normal","testing"]},
  {title:"向量几何",desc:"从坐标到三维直线",ids:["function","vectors","lines"]},
];

const dbName="ib-aa-hl-library";
async function openDb(){return new Promise<IDBDatabase>((resolve,reject)=>{const q=indexedDB.open(dbName,1);q.onupgradeneeded=()=>q.result.createObjectStore("papers",{keyPath:"id"});q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);});}
async function listLocal(){const db=await openDb();return new Promise<Paper[]>((resolve,reject)=>{const q=db.transaction("papers").objectStore("papers").getAll();q.onsuccess=()=>{db.close();resolve(q.result)};q.onerror=()=>reject(q.error);});}
async function saveLocal(p:Paper){const db=await openDb();return new Promise<void>((resolve,reject)=>{const tx=db.transaction("papers","readwrite");tx.objectStore("papers").put(p);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>reject(tx.error);});}
async function deleteLocal(id:string){const db=await openDb();return new Promise<void>((resolve,reject)=>{const tx=db.transaction("papers","readwrite");tx.objectStore("papers").delete(id);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>reject(tx.error);});}

export default function Home(){
  const [view,setView]=useState<View>("home"); const [statuses,setStatuses]=useState<Record<string,Status>>(initialStatuses);
  const [selected,setSelected]=useState("differentiate"); const [topicSearch,setTopicSearch]=useState(""); const [domain,setDomain]=useState<Domain|"全部领域">("全部领域");
  const [tab,setTab]=useState<SourceType|"analytics">("past"); const [papers,setPapers]=useState<Paper[]>(demoPapers); const [paperSearch,setPaperSearch]=useState("");
  const [paperFilter,setPaperFilter]=useState("全部 Paper"); const [difficulty,setDifficulty]=useState("全部难度"); const [showUpload,setShowUpload]=useState(false); const [error,setError]=useState(""); const [hydrated,setHydrated]=useState(false);
  useEffect(()=>{queueMicrotask(()=>{const raw=localStorage.getItem("ib-aa-progress");if(raw)setStatuses({...initialStatuses,...JSON.parse(raw)});setHydrated(true)});listLocal().then(x=>setPapers([...demoPapers,...x])).catch(()=>{});},[]);
  useEffect(()=>{if(hydrated)localStorage.setItem("ib-aa-progress",JSON.stringify(statuses));},[statuses,hydrated]);
  const statusFor=(t:Topic):Status=>statuses[t.id]??(!t.prereq||statuses[t.prereq]==="mastered"?"ready":"locked");
  const mastered=topics.filter(t=>statusFor(t)==="mastered").length; const progress=Math.round(mastered/topics.length*100);
  const filteredTopics=topics.filter(t=>(domain==="全部领域"||t.domain===domain)&&(t.zh.includes(topicSearch)||t.en.toLowerCase().includes(topicSearch.toLowerCase())));
  const selectedTopic=topicById[selected];
  const shownPapers=papers.filter(p=>tab!=="analytics"&&p.sourceType===tab&&(!paperSearch||`${p.title} ${p.source} ${p.year}`.toLowerCase().includes(paperSearch.toLowerCase()))&&(paperFilter==="全部 Paper"||p.paper===paperFilter)&&(difficulty==="全部难度"||p.difficulty===difficulty));
  const sourceCount=(s:SourceType)=>papers.filter(p=>p.sourceType===s).length;
  const domainCounts=useMemo(()=>domains.map(d=>({d,count:papers.filter(p=>p.topicIds.some(id=>topicById[id]?.domain===d)).length,marks:papers.filter(p=>p.topicIds.some(id=>topicById[id]?.domain===d)).reduce((n,p)=>n+p.marks,0)})),[papers]);
  const changeStatus=(id:string,next:Status)=>setStatuses(s=>({...s,[id]:next}));
  const nav=(v:View)=>setView(v);
  const openFile=(p:Paper)=>{if(!p.file)return;const url=URL.createObjectURL(p.file);window.open(url,"_blank","noopener,noreferrer");setTimeout(()=>URL.revokeObjectURL(url),60000)};
  const removePaper=async(id:string)=>{await deleteLocal(id);setPapers(ps=>ps.filter(p=>p.id!==id));};
  const submitUpload=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError("");const fd=new FormData(e.currentTarget);const file=fd.get("file") as File;const title=String(fd.get("title")||"").trim();if(!title)return setError("请填写标题。");if(!file?.size)return setError("请选择 PDF 文件。");if(file.type!=="application/pdf"&&!file.name.toLowerCase().endsWith(".pdf"))return setError("仅支持 PDF 文件。");if(file.size>25*1024*1024)return setError("PDF 不能超过 25 MB。");const topicIds=fd.getAll("topics").map(String);const p:Paper={id:crypto.randomUUID(),title,sourceType:String(fd.get("sourceType")) as SourceType,year:Number(fd.get("year")),session:String(fd.get("session")),paper:String(fd.get("paper")),difficulty:String(fd.get("difficulty")),marks:Number(fd.get("marks")),source:String(fd.get("source"))||"本机上传",topicIds,file};await saveLocal(p);setPapers(ps=>[...ps,p]);setTab(p.sourceType);setShowUpload(false);};
  return <main>
    <header className="topbar"><button className="brand" onClick={()=>nav("home")}><span>∫</span><b>IB AA HL 学习导航<small>SELF-STUDY COMPASS</small></b></button><nav className="desktop-nav" aria-label="主导航">{[["home","首页"],["knowledge","知识地图"],["library","题库"],["paths","学习路径"]].map(([v,l])=><button key={v} className={view===v?"active":""} onClick={()=>nav(v as View)}>{l}</button>)}</nav><div className="progress-pill"><b>{progress}%</b><span>已掌握</span></div></header>
    {view==="home"&&<section className="page home"><div className="hero"><div><p className="eyebrow">继续学习</p><h1>微分与导数法则</h1><p>Calculus · Core · 预计 55 分钟</p><div className="hero-actions"><button className="primary" onClick={()=>{setSelected("differentiate");nav("knowledge")}}>继续学习 →</button><button onClick={()=>nav("paths")}>查看完整路径</button></div></div><div className="ring" style={{"--p":`${progress*3.6}deg`} as React.CSSProperties}><b>{progress}%</b><span>总体掌握度</span></div></div><div className="metrics"><span><b>{mastered}</b>已掌握节点</span><span><b>{papers.filter(p=>!p.demo).length}</b>本机题库文件</span><span><b>5</b>引导式学习路径</span></div><div className="section-head"><p className="eyebrow">CHOOSE YOUR MODE</p><h2>选择学习入口</h2><p>三个独立页面各自聚焦一种学习任务，随时从顶部导航切换。</p></div><div className="entry-grid"><Entry icon="◇" meta="5 大领域 · 30 节点" title="知识地图" desc="按 syllabus 结构浏览定义、前置关系、常见考法与易错点。" tags={["函数","微分","积分"]} onClick={()=>nav("knowledge")}/><Entry icon="▤" meta="真题 · 模拟题 · PDF" title="题库" desc="在一个私人本机题库中管理完整试卷、标签与分布分析。" tags={["本机保存","双分类"]} onClick={()=>nav("library")}/><Entry icon="↗" meta="5 条引导路线" title="学习路径" desc="按照前置关系逐步学习，避免知识点突然跨越。" tags={["循序渐进","可追踪"]} onClick={()=>nav("paths")}/></div></section>}
    {view==="knowledge"&&<section className="page"><PageHead eyebrow="KNOWLEDGE MAP" title="知识地图" desc="先看前置关系，再进入定义、公式、考法与易错点。" badge="30 个代表性节点"/><div className="knowledge-layout"><aside className="knowledge-sidebar"><input aria-label="搜索知识点" placeholder="搜索中英文知识点" value={topicSearch} onChange={e=>setTopicSearch(e.target.value)}/><div className="domain-list"><button className={domain==="全部领域"?"active":""} onClick={()=>setDomain("全部领域")}>全部领域 <b>30</b></button>{domains.map(d=><button key={d} className={domain===d?"active":""} onClick={()=>setDomain(d)}>{d}<b>6</b></button>)}</div><div className="topic-list">{filteredTopics.map(t=><button key={t.id} className={selected===t.id?"active":""} onClick={()=>setSelected(t.id)}><span><b>{t.zh}</b><small>{t.en}</small></span><em className={statusFor(t)}>{statusLabel(statusFor(t))}</em></button>)}</div></aside><article className="topic-detail"><p className="eyebrow">{selectedTopic.domain} · AHL</p><h2>{selectedTopic.zh}</h2><h3>{selectedTopic.en}</h3><span className={`status ${statusFor(selectedTopic)}`}>{statusLabel(statusFor(selectedTopic))}</span><p className="lead">掌握这一节点的定义、表示与典型题型，并能解释每一步公式来源。</p><Detail title="核心内容" items={selectedTopic.core}/><Detail title="常见真题考法" items={selectedTopic.exam}/><Detail title="易错点" items={selectedTopic.mistakes}/>{selectedTopic.prereq&&<p className="prereq">前置知识：{statusFor(topicById[selectedTopic.prereq])==="mastered"?"✓":"○"} {topicById[selectedTopic.prereq].zh}</p>}<div className="detail-actions">{statusFor(selectedTopic)!=="mastered"?<><button onClick={()=>changeStatus(selectedTopic.id,"learning")}>设为学习中</button><button className="primary" onClick={()=>changeStatus(selectedTopic.id,"mastered")}>标记为已掌握</button></>:<button onClick={()=>changeStatus(selectedTopic.id,"ready")}>取消已掌握</button>}</div></article></div></section>}
    {view==="library"&&<section className="page"><PageHead eyebrow="DOCUMENT LIBRARY" title="题库" desc="完整 PDF 与元数据保存在当前浏览器；真题和模拟题使用同一标签体系。" action={<button className="primary" onClick={()=>setShowUpload(true)}>↑ 上传 PDF</button>}/><div className="notice"><b>演示数据</b>预置频次仅用于验证界面；上传自己的文件后会单独标为“本机”。</div><div className="tabs" role="tablist" aria-label="题库类型"><button role="tab" aria-selected={tab==="past"} onClick={()=>setTab("past")}>真题 {sourceCount("past")}</button><button role="tab" aria-selected={tab==="mock"} onClick={()=>setTab("mock")}>模拟题 {sourceCount("mock")}</button><button role="tab" aria-selected={tab==="analytics"} onClick={()=>setTab("analytics")}>分布分析</button></div>{tab==="analytics"?<Analytics counts={domainCounts} papers={papers}/>:<><div className="filters"><input aria-label="搜索题库" placeholder="搜索标题、来源或年份" value={paperSearch} onChange={e=>setPaperSearch(e.target.value)}/><select aria-label="筛选 Paper" value={paperFilter} onChange={e=>setPaperFilter(e.target.value)}><option>全部 Paper</option><option>Paper 1</option><option>Paper 2</option><option>Paper 3</option></select><select aria-label="筛选难度" value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option>全部难度</option><option>基础</option><option>中等</option><option>较难</option><option>挑战</option></select></div><div className="paper-grid">{shownPapers.map(p=><article className="paper-card" key={p.id}><div className="card-meta"><span>{p.demo?"演示元数据":"本机 PDF"}</span><em>{p.difficulty}</em></div><h3>{p.title}</h3><p>{p.year} · {p.session} · {p.paper} · {p.marks} 分</p><div className="tags">{p.topicIds.map(id=><span key={id}>{topicById[id]?.zh}</span>)}</div><small>来源：{p.source}</small><div className="paper-actions"><button disabled={!p.file} onClick={()=>openFile(p)}>{p.file?"打开 PDF":"未附 PDF"}</button>{!p.demo&&<button className="danger" onClick={()=>removePaper(p.id)}>删除</button>}</div></article>)}</div></>}</section>}
    {view==="paths"&&<section className="page"><PageHead eyebrow="GUIDED ROUTES" title="学习路径" desc="严格按“知识点讲解 → 基础检查 → 例题 → 真题”推进。" badge="5 条路线"/><div className="path-grid">{paths.map((p,i)=><article className="path-card" key={p.title}><span>0{i+1}</span><h2>{p.title}</h2><p>{p.desc}</p><ol>{p.ids.map((id,n)=><li key={id} className={statusFor(topicById[id])}><b>{n+1}</b><span>{topicById[id].zh}<small>{topicById[id].en}</small></span><em>{statusLabel(statusFor(topicById[id]))}</em></li>)}</ol><button onClick={()=>{setSelected(p.ids.find(id=>statusFor(topicById[id])!=="mastered")||p.ids[0]);nav("knowledge")}}>进入路径 →</button></article>)}</div></section>}
    <nav className="mobile-nav">{[["home","首页"],["knowledge","知识"],["library","题库"],["paths","路径"]].map(([v,l])=><button key={v} className={view===v?"active":""} onClick={()=>nav(v as View)}>{l}</button>)}</nav>
    {showUpload&&<div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-label="上传真题"><form onSubmit={submitUpload}><div className="modal-head"><div><p className="eyebrow">LOCAL PDF LIBRARY</p><h2>上传真题或模拟题</h2></div><button type="button" aria-label="关闭" onClick={()=>setShowUpload(false)}>×</button></div><div className="notice"><b>仅保存在本机</b>文件不会上传服务器。清除浏览器网站数据会删除这些 PDF。</div><label className="file-picker">↑<b>选择 PDF 文件</b><small>最大 25 MB，仅支持 PDF</small><input type="file" name="file" accept="application/pdf,.pdf" onChange={(e:ChangeEvent<HTMLInputElement>)=>{if(e.target.files?.[0])setError("")}}/></label><div className="form-grid"><label>标题<input name="title" placeholder="例如：M24 TZ1 Paper 1"/></label><label>类型<select name="sourceType"><option value="past">真题</option><option value="mock">模拟题</option></select></label><label>年份<input name="year" type="number" defaultValue={2026}/></label><label>考季 / 批次<input name="session" defaultValue="May" placeholder="May / November / Mock"/></label><label>Paper<select name="paper"><option>Paper 1</option><option>Paper 2</option><option>Paper 3</option></select></label><label>难度<select name="difficulty"><option>基础</option><option>中等</option><option>较难</option><option>挑战</option></select></label><label>总分 / 相关分值<input name="marks" type="number" defaultValue={10}/></label><label>来源<input name="source" placeholder="学校、教师或资料来源"/></label></div><label>知识点标签（可多选）<select name="topics" multiple size={7}>{topics.map(t=><option key={t.id} value={t.id}>{t.zh} · {t.en}</option>)}</select><small>Mac 按住 Command 可多选。</small></label>{error&&<p className="error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" onClick={()=>setShowUpload(false)}>取消</button><button className="primary">保存到本机</button></div></form></div></div>}
  </main>
}

function statusLabel(s:Status){return {locked:"未解锁",ready:"可学习",learning:"学习中",mastered:"已掌握"}[s]}
function Entry({icon,meta,title,desc,tags,onClick}:{icon:string;meta:string;title:string;desc:string;tags:string[];onClick:()=>void}){return <article className="entry-card"><span className="entry-icon">{icon}</span><p className="eyebrow">{meta}</p><h2>{title}</h2><p>{desc}</p><div className="tags">{tags.map(t=><span key={t}>{t}</span>)}</div><button onClick={onClick}>打开{title} →</button></article>}
function PageHead({eyebrow,title,desc,badge,action}:{eyebrow:string;title:string;desc:string;badge?:string;action?:React.ReactNode}){return <div className="page-head"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{desc}</p></div>{badge&&<span className="badge">{badge}</span>}{action}</div>}
function Detail({title,items}:{title:string;items:string[]}){return <div className="detail-block"><h4>{title}</h4><ul>{items.map(x=><li key={x}>{x}</li>)}</ul></div>}
function Analytics({counts,papers}:{counts:{d:Domain;count:number;marks:number}[];papers:Paper[]}){const max=Math.max(...counts.map(x=>x.marks),1);return <div className="analytics"><section><p className="eyebrow">TOPIC COVERAGE</p><h2>领域分布 <small>{papers.length} 条记录</small></h2>{counts.map(x=><div className="bar-row" key={x.d}><span>{x.d}</span><div><i style={{width:`${x.marks/max*100}%`}}/></div><b>{x.count} 条 · {x.marks} 分</b></div>)}</section><section><p className="eyebrow">PAPER MIX</p><h2>试卷分布</h2><div className="big-numbers">{["Paper 1","Paper 2","Paper 3"].map(p=><span key={p}><b>{papers.filter(x=>x.paper===p).length}</b>{p.replace("aper ","")}</span>)}</div><p className="eyebrow source">SOURCE MIX</p><div className="big-numbers"><span><b>{papers.filter(x=>x.sourceType==="past").length}</b>真题</span><span><b>{papers.filter(x=>x.sourceType==="mock").length}</b>模拟题</span></div></section></div>}
